# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: fe830791a7552708f4b94bd26fcca065476c31f4f9719b00c4ad39b7d91bb0095ba4c42b178b2fc22bf0031b9d40c8efa82b8b1d9d23f424e62e753a99b57557

test:
  secret_key_base: f6d70ed81572c9c2d4d8d5ff0d22de824faa39c0f898d20582336f23207843f7647399e8b4cc07294610e7a2fc46158e395db750e60d488529e92f37c66ff4fc

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
